/* tslint:disable */
/* eslint-disable */
/**
 * XRPL GPT Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.9-beta.1
 * Contact: dangell@transia.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { GPTCompletionCreateRequest } from '../models';
import { GPTCompletionCreateResponse } from '../models';
/**
 * GptApi - axios parameter creator
 * @export
 */
export const GptApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a gpt
         * @param {GPTCompletionCreateRequest} body GPT Completion Created Successful
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gptCompletionCreate: async (body: GPTCompletionCreateRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling gptCompletionCreate.');
            }
            const localVarPath = `/gpt/completion/create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GptApi - functional programming interface
 * @export
 */
export const GptApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a gpt
         * @param {GPTCompletionCreateRequest} body GPT Completion Created Successful
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gptCompletionCreate(body: GPTCompletionCreateRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<GPTCompletionCreateResponse>>> {
            const localVarAxiosArgs = await GptApiAxiosParamCreator(configuration).gptCompletionCreate(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * GptApi - factory interface
 * @export
 */
export const GptApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Create a gpt
         * @param {GPTCompletionCreateRequest} body GPT Completion Created Successful
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gptCompletionCreate(body: GPTCompletionCreateRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<GPTCompletionCreateResponse>> {
            return GptApiFp(configuration).gptCompletionCreate(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GptApi - object-oriented interface
 * @export
 * @class GptApi
 * @extends {BaseAPI}
 */
export class GptApi extends BaseAPI {
    /**
     * 
     * @summary Create a gpt
     * @param {GPTCompletionCreateRequest} body GPT Completion Created Successful
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GptApi
     */
    public async gptCompletionCreate(body: GPTCompletionCreateRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<GPTCompletionCreateResponse>> {
        return GptApiFp(this.configuration).gptCompletionCreate(body, options).then((request) => request(this.axios, this.basePath));
    }
}
