/* tslint:disable */
/* eslint-disable */
/**
 * XRPL GPT Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.9-beta.1
 * Contact: dangell@transia.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { IndexModelCreateRequest } from '../models';
import { MessageResponse } from '../models';
/**
 * IndexModelApi - axios parameter creator
 * @export
 */
export const IndexModelApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create an index model
         * @param {IndexModelCreateRequest} body Index Model Params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        indexModelCreate: async (body: IndexModelCreateRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling indexModelCreate.');
            }
            const localVarPath = `/indexModel/create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IndexModelApi - functional programming interface
 * @export
 */
export const IndexModelApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create an index model
         * @param {IndexModelCreateRequest} body Index Model Params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async indexModelCreate(body: IndexModelCreateRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<MessageResponse>>> {
            const localVarAxiosArgs = await IndexModelApiAxiosParamCreator(configuration).indexModelCreate(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * IndexModelApi - factory interface
 * @export
 */
export const IndexModelApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Create an index model
         * @param {IndexModelCreateRequest} body Index Model Params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async indexModelCreate(body: IndexModelCreateRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<MessageResponse>> {
            return IndexModelApiFp(configuration).indexModelCreate(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * IndexModelApi - object-oriented interface
 * @export
 * @class IndexModelApi
 * @extends {BaseAPI}
 */
export class IndexModelApi extends BaseAPI {
    /**
     * 
     * @summary Create an index model
     * @param {IndexModelCreateRequest} body Index Model Params
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IndexModelApi
     */
    public async indexModelCreate(body: IndexModelCreateRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<MessageResponse>> {
        return IndexModelApiFp(this.configuration).indexModelCreate(body, options).then((request) => request(this.axios, this.basePath));
    }
}
