/* tslint:disable */
/* eslint-disable */
/**
 * XRPL GPT Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.9-beta.1
 * Contact: dangell@transia.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { PlaygroundPromptRequest } from '../models';
import { PlaygroundPromptResponse } from '../models';
/**
 * PlaygroundApi - axios parameter creator
 * @export
 */
export const PlaygroundApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Prompt Completion for playground
         * @param {PlaygroundPromptRequest} body Playground Prompt Params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        playgroundPrompt: async (body: PlaygroundPromptRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling playgroundPrompt.');
            }
            const localVarPath = `/plyground/prompt`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PlaygroundApi - functional programming interface
 * @export
 */
export const PlaygroundApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Prompt Completion for playground
         * @param {PlaygroundPromptRequest} body Playground Prompt Params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async playgroundPrompt(body: PlaygroundPromptRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PlaygroundPromptResponse>>> {
            const localVarAxiosArgs = await PlaygroundApiAxiosParamCreator(configuration).playgroundPrompt(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * PlaygroundApi - factory interface
 * @export
 */
export const PlaygroundApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Prompt Completion for playground
         * @param {PlaygroundPromptRequest} body Playground Prompt Params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async playgroundPrompt(body: PlaygroundPromptRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<PlaygroundPromptResponse>> {
            return PlaygroundApiFp(configuration).playgroundPrompt(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PlaygroundApi - object-oriented interface
 * @export
 * @class PlaygroundApi
 * @extends {BaseAPI}
 */
export class PlaygroundApi extends BaseAPI {
    /**
     * 
     * @summary Prompt Completion for playground
     * @param {PlaygroundPromptRequest} body Playground Prompt Params
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlaygroundApi
     */
    public async playgroundPrompt(body: PlaygroundPromptRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<PlaygroundPromptResponse>> {
        return PlaygroundApiFp(this.configuration).playgroundPrompt(body, options).then((request) => request(this.axios, this.basePath));
    }
}
