/* tslint:disable */
/* eslint-disable */
/**
 * XRPL GPT Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.9-beta.1
 * Contact: dangell@transia.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PlaygroundPromptRequest
 */
export interface PlaygroundPromptRequest {
    /**
     * 
     * @type {string}
     * @memberof PlaygroundPromptRequest
     */
    accountId: string;
    /**
     * 
     * @type {string}
     * @memberof PlaygroundPromptRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PlaygroundPromptRequest
     */
    prompt: string;
    /**
     * 
     * @type {string}
     * @memberof PlaygroundPromptRequest
     */
    modelName: string;
    /**
     * 
     * @type {number}
     * @memberof PlaygroundPromptRequest
     */
    temperature: number;
    /**
     * 
     * @type {number}
     * @memberof PlaygroundPromptRequest
     */
    maxTokens: number;
    /**
     * 
     * @type {number}
     * @memberof PlaygroundPromptRequest
     */
    topP: number;
    /**
     * 
     * @type {number}
     * @memberof PlaygroundPromptRequest
     */
    frequencyPenalty: number;
    /**
     * 
     * @type {number}
     * @memberof PlaygroundPromptRequest
     */
    presencePenalty: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof PlaygroundPromptRequest
     */
    stop: Array<string>;
}
